set(CMAKE_CXX_STANDARD 20)

add_executable(136a 136a.cpp)
add_executable(1330a 1330a.cpp)
add_executable(1352a 1352a.cpp)
add_executable(1404a 1404a.cpp)
add_executable(1512c 1512c.cpp)
add_executable(1569a 1569a.cpp)
add_executable(1670b 1670b.cpp)
add_executable(1717b.v01 1717b.v01.cpp)
add_executable(1717b.v02 1717b.v02.cpp)
add_executable(1721b 1721b.cpp)
add_executable(1872a 1872a.cpp)
add_executable(1873c 1873c.cpp)
add_executable(1873d 1873d.cpp)
add_executable(1900b 1900b.cpp)
add_executable(1971c 1971c.cpp)
add_executable(2137a 2137a.cpp)
add_executable(2149a 2149a.cpp)
add_executable(2149a 2149a.cpp)
add_executable(263a 263a.cpp)
add_executable(271a 271a.cpp)
add_executable(276a 276a.cpp)
add_executable(318a 318a.cpp)
add_executable(339b 339b.cpp)
add_executable(469a 469a.cpp)
add_executable(4a 4a.cpp)
add_executable(617a 617a.cpp)
add_executable(977a 977a.cpp)
add_executable(978a 978a.cpp)
add_executable(978b 978b.cpp)
